name: SideWaysLogs
main: main.SideWaysLogs
version: 2.1.3e
description: >
             Locking vertical orientation when placing logs.
commands:
  swl:
    description: Basic Command For SideWaysLogs.