name: SideWaysLogs
main: com.dbteku.main.SideWaysLogs
version: 3.0.1
api-version: 1.13
description: >
             Locking vertical orientation when placing logs.
commands:
  swl:
    description: Basic Command For SideWaysLogs.