name: SideWaysLogs
main: com.dbteku.main.SideWaysLogs
version: 2.1.9.1
description: >
             Locking vertical orientation when placing logs.
commands:
  swl:
    description: Basic Command For SideWaysLogs.